# NBA Teams
EAST_TEAMS = [
    'BOSTON CELTICS', 'PHILADELPHIA 76ERS', 'NEW YORK KNICKS', 'BROOKLYN NETS', 'TORONTO RAPTORS',
    'MILWAUKEE BUCKS', 'INDIANA PACERS', 'CLEVELAND CAVALIERS', 'CHICAGO BULLS', 'DETROIT PISTONS',
    'MIAMI HEAT', 'ORLANDO MAGIC', 'ATLANTA HAWKS', 'CHARLOTTE HORNETS', 'WASHINGTON WIZARDS'
]

WEST_TEAMS = [
    'MINNESOTA TIMBERWOLVES', 'OKLAHOMA CITY THUNDER', 'DENVER NUGGETS', 'UTAH JAZZ',
    'PORTLAND TRAIL BLAZERS', 'LOS ANGELES CLIPPERS', 'SACRAMENTO KINGS', 'PHOENIX SUNS',
    'LOS ANGELES LAKERS', 'GOLDEN STATE WARRIORS', 'NEW ORLEANS PELICANS', 'DALLAS MAVERICKS',
    'HOUSTON ROCKETS', 'MEMPHIS GRIZZLIES', 'SAN ANTONIO SPURS'
]

EAST_OPENING_STANDINGS = {
    'BOSTON CELTICS': (0, 0),
    'NEW YORK KNICKS': (0, 0),
    'PHILADELPHIA 76ERS': (0, 0),
    'BROOKLYN NETS': (0, 0),
    'TORONTO RAPTORS': (0, 0),
    'CLEVELAND CAVALIERS': (0, 0),
    'MILWAUKEE BUCKS': (0, 0),
    'INDIANA PACERS': (0, 0),
    'CHICAGO BULLS': (0, 0),
    'DETROIT PISTONS': (0, 0),
    'ORLANDO MAGIC': (0, 0),
    'MIAMI HEAT': (0, 0),
    'ATLANTA HAWKS': (0, 0),
    'CHARLOTTE HORNETS': (0, 0),
    'WASHINGTON WIZARDS': (0, 0)
}

WEST_OPENING_STANDINGS = {
    'MINNESOTA TIMBERWOLVES': (0, 0),
    'OKLAHOMA CITY THUNDER': (0, 0),
    'DENVER NUGGETS': (0, 0),
    'UTAH JAZZ': (0, 0),
    'PORTLAND TRAIL BLAZERS': (0, 0),
    'LOS ANGELES CLIPPERS': (0, 0),
    'PHOENIX SUNS': (0, 0),
    'SACRAMENTO KINGS': (0, 0),
    'GOLDEN STATE WARRIORS': (0, 0),
    'LOS ANGELES LAKERS': (0, 0),
    'NEW ORLEANS PELICANS': (0, 0),
    'DALLAS MAVERICKS': (0, 0),
    'HOUSTON ROCKETS': (0, 0),
    'MEMPHIS GRIZZLIES': (0, 0),
    'SAN ANTONIO SPURS': (0, 0)
}

# NBA Finals
NBA_FINALS_APP_BY_SEED = [49, 23, 13, 4, 1, 2, 0, 2]
NBA_FINALS_APP_BY_SEED_GAUSSIAN_SMOOTHED = [38, 27, 14, 6, 2, 1, 1, 1]

# NBA Seeds
NBA_SEEDS = [1, 2, 3, 4, 5, 6, 7, 8]

# Simulation Constants
SIMULATION_COUNT = 25000
OPENING_NIGHT_CLI = 0.88

# NBA Matchups
OPENING_NIGHT_EVERY_TEAM = [
    ['BOSTON CELTICS', 'PHILADELPHIA 76ERS'], ['NEW YORK KNICKS', 'BROOKLYN NETS'],
    ['TORONTO RAPTORS', 'MILWAUKEE BUCKS'], ['INDIANA PACERS', 'CLEVELAND CAVALIERS'],
    ['CHICAGO BULLS', 'DETROIT PISTONS'], ['MIAMI HEAT', 'ORLANDO MAGIC'],
    ['ATLANTA HAWKS', 'CHARLOTTE HORNETS'], ['MINNESOTA TIMBERWOLVES', 'OKLAHOMA CITY THUNDER'],
    ['DENVER NUGGETS', 'UTAH JAZZ'], ['PORTLAND TRAIL BLAZERS', 'LOS ANGELES CLIPPERS'],
    ['SACRAMENTO KINGS', 'PHOENIX SUNS'], ['LOS ANGELES LAKERS', 'GOLDEN STATE WARRIORS'],
    ['NEW ORLEANS PELICANS', 'DALLAS MAVERICKS'], ['HOUSTON ROCKETS', 'MEMPHIS GRIZZLIES'],
    ['SAN ANTONIO SPURS', 'WASHINGTON WIZARDS']
]

# Odds of Winning the Title by Seed (regardless of conference)
SEED_CHAMPIONSHIP_ODDS = {
    '1': .353, '2': .303, '3': .185, '4': .086, '5': .035, '6': .015, '7': .012, '8': .011
}

# Conference Seed Championship Odds
CONF_SEED_CHAMPIONSHIP_ODDS = {
    '1': 0.1765, '2': 0.1515, '3': 0.0925, '4': 0.043, '5': 0.0175, '6': 0.0075, '7': 0.006, '8': 0.0055
}
